<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>finxml-gen</AssemblyName>
    <RootNamespace>FinXmlProcessor.TestDataGenerator</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>
</Project>
