<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>finxml</AssemblyName>
    <RootNamespace>FinXmlProcessor.Worker</RootNamespace>
    <SelfContained>false</SelfContained>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../FinXmlProcessor.Infrastructure/FinXmlProcessor.Infrastructure.csproj" />
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../../samples/profiles/*.json" Link="samples/profiles/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../samples/input/demo-transactions.xml" Link="samples/input/demo-transactions.xml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
