<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>finxml</AssemblyName>
    <RootNamespace>FinXmlProcessor.Worker</RootNamespace>
    <SelfContained>false</SelfContained>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../FinXmlProcessor.Infrastructure/FinXmlProcessor.Infrastructure.csproj" />
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>
</Project>
