<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FinXmlProcessor.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../FinXmlProcessor.Domain/FinXmlProcessor.Domain.csproj" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="NodaTime" />
    <PackageReference Include="JsonSchema.Net" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Profiles/Schema/mapping-profile.schema.json" LogicalName="FinXmlProcessor.Application.mapping-profile.schema.json" />
  </ItemGroup>
</Project>
